# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(408, 685)
        SignUp.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.centralwidget = QtWidgets.QWidget(SignUp)
        self.centralwidget.setObjectName("centralwidget")
        self.i_username = QtWidgets.QLineEdit(self.centralwidget)
        self.i_username.setGeometry(QtCore.QRect(40, 110, 331, 41))
        self.i_username.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 153, 0);\n"
"font: 15pt \"Yu Gothic UI\";")
        self.i_username.setObjectName("i_username")
        self.l_topic = QtWidgets.QLabel(self.centralwidget)
        self.l_topic.setGeometry(QtCore.QRect(150, 10, 121, 51))
        self.l_topic.setStyleSheet("font: 26pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);")
        self.l_topic.setObjectName("l_topic")
        self.l_login = QtWidgets.QLabel(self.centralwidget)
        self.l_login.setGeometry(QtCore.QRect(90, 630, 231, 21))
        self.l_login.setStyleSheet("color: rgb(255, 153, 0);\n"
"font: 13pt \"Yu Gothic UI\";")
        self.l_login.setObjectName("l_login")
        self.l_fullname = QtWidgets.QLabel(self.centralwidget)
        self.l_fullname.setGeometry(QtCore.QRect(40, 160, 91, 31))
        self.l_fullname.setStyleSheet("font: 12pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.l_fullname.setObjectName("l_fullname")
        self.l_username = QtWidgets.QLabel(self.centralwidget)
        self.l_username.setGeometry(QtCore.QRect(40, 80, 91, 31))
        self.l_username.setStyleSheet("font: 12pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.l_username.setObjectName("l_username")
        self.i_fullname = QtWidgets.QLineEdit(self.centralwidget)
        self.i_fullname.setGeometry(QtCore.QRect(40, 190, 331, 41))
        self.i_fullname.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 153, 0);\n"
"font: 15pt \"Yu Gothic UI\";")
        self.i_fullname.setText("")
        self.i_fullname.setObjectName("i_fullname")
        self.b_singup = QtWidgets.QPushButton(self.centralwidget)
        self.b_singup.setGeometry(QtCore.QRect(40, 570, 331, 41))
        self.b_singup.setStyleSheet("background-color: rgb(255, 153, 0);\n"
"font: 16pt \"Yu Gothic UI\";")
        self.b_singup.setObjectName("b_singup")
        self.l_email = QtWidgets.QLabel(self.centralwidget)
        self.l_email.setGeometry(QtCore.QRect(40, 240, 91, 31))
        self.l_email.setStyleSheet("font: 12pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.l_email.setObjectName("l_email")
        self.i_email = QtWidgets.QLineEdit(self.centralwidget)
        self.i_email.setGeometry(QtCore.QRect(40, 270, 331, 41))
        self.i_email.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 153, 0);\n"
"font: 15pt \"Yu Gothic UI\";")
        self.i_email.setText("")
        self.i_email.setObjectName("i_email")
        self.i_password = QtWidgets.QLineEdit(self.centralwidget)
        self.i_password.setGeometry(QtCore.QRect(40, 350, 331, 41))
        self.i_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 153, 0);\n"
"font: 15pt \"Yu Gothic UI\";")
        self.i_password.setText("")
        self.i_password.setObjectName("i_password")
        self.l_password = QtWidgets.QLabel(self.centralwidget)
        self.l_password.setGeometry(QtCore.QRect(40, 320, 91, 31))
        self.l_password.setStyleSheet("font: 12pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.l_password.setObjectName("l_password")
        self.i_password_confirm = QtWidgets.QLineEdit(self.centralwidget)
        self.i_password_confirm.setGeometry(QtCore.QRect(40, 430, 331, 41))
        self.i_password_confirm.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 153, 0);\n"
"font: 15pt \"Yu Gothic UI\";")
        self.i_password_confirm.setText("")
        self.i_password_confirm.setObjectName("i_password_confirm")
        self.l_password_confirm = QtWidgets.QLabel(self.centralwidget)
        self.l_password_confirm.setGeometry(QtCore.QRect(40, 400, 171, 31))
        self.l_password_confirm.setStyleSheet("font: 12pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.l_password_confirm.setObjectName("l_password_confirm")
        self.l_dateofbirth = QtWidgets.QLabel(self.centralwidget)
        self.l_dateofbirth.setGeometry(QtCore.QRect(40, 480, 171, 31))
        self.l_dateofbirth.setStyleSheet("font: 12pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.l_dateofbirth.setObjectName("l_dateofbirth")
        self.i_date = QtWidgets.QDateEdit(self.centralwidget)
        self.i_date.setGeometry(QtCore.QRect(40, 510, 331, 41))
        self.i_date.setStyleSheet("font: 15pt \"Yu Gothic UI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.i_date.setObjectName("i_date")
        SignUp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SignUp)
        self.statusbar.setObjectName("statusbar")
        SignUp.setStatusBar(self.statusbar)

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "Sign Up"))
        self.l_topic.setText(_translate("SignUp", "Sign Up"))
        self.l_login.setText(_translate("SignUp", "Have an Account? Log in here"))
        self.l_fullname.setText(_translate("SignUp", "Full Name:"))
        self.l_username.setText(_translate("SignUp", "Username:"))
        self.b_singup.setText(_translate("SignUp", "Sign Up"))
        self.l_email.setText(_translate("SignUp", "Email:"))
        self.l_password.setText(_translate("SignUp", "Password:"))
        self.l_password_confirm.setText(_translate("SignUp", "Confirm Password:"))
        self.l_dateofbirth.setText(_translate("SignUp", "Date of Birth:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUp = QtWidgets.QMainWindow()
    ui = Ui_SignUp()
    ui.setupUi(SignUp)
    SignUp.show()
    sys.exit(app.exec())
